# <span style="color:blue"> MBA em Ciência de Dados</span>
# <span style="color:blue">Programação para Ciência de Dados</span>

## <span style="color:blue">Numpy Parte I - Avaliação</span>
**Material Produzido por Luis Gustavo Nonato**<br>
**Cemeai - ICMC/USP São Carlos**

<font color='red'> As respostas da avaliação devem ser inseridas no moodle </font>

In [1]:
import numpy as np

### Exercício 1)
Considere o array `X` como descrito abaixo:
```python
X = np.arange(100).reshape(10,10)
```
Utilizando indexação, gere uma nova matriz `Y`, que contenha apenas as linhas com índices 1,5 e 7 e colunas de 1 a 3 de `X`.
O resultado do comando
```python
print(Y.ravel())
```
será:

a) [11 12 51 52 71 72]<br>
b) [11 12 13 51 52 53 71 72 73]<br>
c) [10 11 12 13 50 51 52 53 70 71 72 73]<br>
d) [11 15 17 21 25 27 31 35 37]

In [12]:
X = np.arange(100).reshape(10,10)
print(X)
print('---')
#Solucao
Y = X[[1, 5, 7,], 1:4]
print(Y.ravel())

# RESPOSTA B

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]
---
[11 12 13 51 52 53 71 72 73]


### Exercício 2)
Considerando o array `X` do exercício 1). Qual alternativa abaixo retorna uma **cópia** de um subconjunto de elementos em `X` e **não uma view**?

a) Y = X[1:3,[0,2,3]]<br>
b) Y = X[1:3,2:]<br>
c) Y = X[:,5:8]<br>
d) Y = X[0::2,5:-1]

**Dica:** Verifique o que acontece com `X` se algum elemento de `Y` é modificado

In [17]:
# Solucao
# Testando a Opção A (Mistura de Slice e Lista)
Y_a = X[1:3, [0, 2, 3]]
Y_a[0, 0] = 999  # Alterando Y
print(f"X[1, 0] mudou? {X[1, 0]}") # Deve continuar 10 -> CÓPIA

# Testando a Opção B (Apenas Slices)
Y_b = X[1:3, 2:]
Y_b[0, 0] = 888  # Alterando Y
print(f"X[1, 2] mudou? {X[1, 2]}") # Vai mudar para 888 -> VIEW

# RESPOSTA A

X[1, 0] mudou? 10
X[1, 2] mudou? 888


### Exercício 3)
Considere o array `A` abaixo:
```python
[[ 2 19 16  1 12  7]
 [ 5 19 18 17  9  3]
 [16  4 18 11  4  2]
 [ 6  2 18 14 15 15]
 [ 4  8  1 14 19 13]]
```
Qual das alternativas abaixo corresponde ao número de dimensões (ndim), a forma (shape) e ao número de elementos (size) no array, respectivamente?

a) (5, 6) 2 2<br>
b) 2 (5, 6) 2<br>
c) (5, 6) 2 30<br>
d) 2 (5, 6) 30

In [18]:
A = np.array([[ 2, 19, 16,  1, 12,  7],
 [ 5, 19, 18, 17,  9,  3],
 [16,  4, 18, 11,  4,  2],
 [ 6,  2, 18, 14, 15, 15],
 [ 4,  8,  1, 14, 19, 13]])

# Solucao
print(A.ndim) #dimensões
print(A.shape) #forma
print(A.size) #elementos

# RESPOSTA D

2
(5, 6)
30


### Exercício 4)
Considere o numpy array `A` do exercício 3). Escreva um código para criar uma máscara booleana para selecionar **todos** os **elementos pares** de `A` e armazená-los em um novo array *unidimensional* `B`. O resultado do comando
```python
print(B.size)
```
será:<br>
a) 13<br>
b) 15<br>
c) 16<br>
d) 17

In [19]:
# Solucao
mask = (A % 2 == 0)
B = A[mask]
print(B.size)

# RESPOSTA C


16


### Exercício 5)
Ainda considerando o array `A` do exercício 3), qual alternativa melhor explica o que o código abaixo está realizando:
```python
l_mask = [(i%2!=0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
```

a) insere elementos -1 nas linhas e colunas pares de `A` utilizando uma máscara booleana<br>
b) insere elementos -1 nas posições com índices ímpares (linha e coluna) de `A` utilizando uma máscara booleana<br>
c) insere elementos -1 nas linhas com índices ímpares e colunas pares de `A` utilizando uma máscara booleana<br>
d) troca os elementos impares da matriz por -1 utilizando uma máscara booleana

In [20]:
l_mask = [(i%2!=0) and (j%2!=0) for i in range(A.shape[0]) for j in range(A.shape[1])]
mask = np.array(l_mask).reshape(A.shape)
A[mask] = -1
print(A)

# RESPOSTA B

[[ 2 19 16  1 12  7]
 [ 5 -1 18 -1  9 -1]
 [16  4 18 11  4  2]
 [ 6 -1 18 -1 15 -1]
 [ 4  8  1 14 19 13]]
